### PR TITLE
Fix integer defaults for testing_create

### PR DESCRIPTION
**Pull request by nZac**

### CODE REVIEW

**Comment by rsyring** [comment]
Are you only overriding this in the parent `testing_create()` or are you setting the value every time you call `testing_create()`?

**Comment by nZac** [comment]
You could do it at both.

There is a default for when you don't care, you could set it at the class level, or set it at the test level if for some reason you need it.

**Comment by rsyring** [comment]
Have you been using this in FIS?  How is it working out?

**Comment by nZac** [comment]
Yes, we are: https://github.com/level12/fis-residuals/blob/c121fd5e11756fc15f710c65e2e3dd2b796b6942/fisresid/model/utils.py#L630-L668

And in a test: https://github.com/level12/fis-residuals/blob/7cb937fac797ecf235274ebebb91cbb33925ad7d/fisresid/tests/test_calc.py#L2217-L2229

The point is, I don't want to have to set every field, but I do need a known value in the field.

**Pull request merged**
