### PR TITLE
Add ability to randomly fill EmailType columns

### PR DESCRIPTION
**Pull request by 3noch**
Using the infamous `randemail` function.

### CODE REVIEW

**Comment by 3noch** [comment]
@rsyring @nZac Ready for you.

**Comment by rsyring** [comment]
Should adding the wheel be part of this PR?

**Comment by 3noch** [comment]
That would probably qualify as another invisible bar to me.

**Comment by rsyring** [comment]
do you need the wheels to get the tests or code to run?

**Comment by 3noch** [comment]
I did.

**Comment by rsyring** [comment]
Sorry, what I really meant to ask was, are the wheels added/updated directly related to the code you added/modified.  I.e. did your changes result in new wheels being needed for the project.  As opposed to, was the project already using wheels that just weren't built yet for OSX.  

Since there are no changes to setup.py requirements or the pip requirement files, I'm guessing these are not new dependencies but rather that you just needed the wheels built...i.e. the project was short some OSX wheels in the wheelhouse.  In that case, I'd say, in the future, remove the wheels from this PR and make that a separate PR.

But, for now, I'll just accept it as-is.  The commit is at least separate.

**Comment by 3noch** [comment]
Great. Thank you! I'll be sure to do that next time. Teams seem to care more or less about that type of thing depending on how "pure" they like to be about commit and PR history.

**Pull request merged**
