### PR TITLE
Use whatever version of JSON flask is using

### PR DESCRIPTION
**Pull request by nZac**
The packages that end up using keg and keg elements should determine
which JSON encoder/decoder to use. This is not as simple as just
checking for simplejson / stdlib json since flask supports completely
overriding the encoders and decords when creating an application.

See http://flask.readthedocs.org/en/latest/api/#module-flask.json for
more details.

### CODE REVIEW

**Comment by rsyring** [comment]
Per our conversation, I'd like to simply remove this functionality and stick with using "|tojson" in the templates.

**Comment by rsyring** [comment]
Can this be closed?

**Comment by nZac** [comment]
I would think it needs to be merged not closed. This removes the JSON functionality and forces `|tojson` as the paradigm.

**Comment by rsyring** [comment]
Oh, ic.  The code is different than the first comment.

**Pull request merged**
